site_name: SMI
site_url: https://github.com/jorgehcorrea/documentation/tree/master/docs/index.md
site_description: Sistema de Monitoreo Inalambrico
site_author: 

repo_url: https://github.com/jorgehcorrea/documentation
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - User Documentation:
        - 433 mhz: 433.md
        - nRf24L01: nRf24L01.md
        - esp8266: esp8266.md 
        - esp32.md
        - fabzoi_system: fabzoi_system.md
        - 433_integration: 433_int.md
        - wi-fi_integration: wi-fi_int.md


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list

copyright: Copyright &copy; 2020 <a href="www.jhc.design">Jorge Correa</a> 
  MkDocs Support:<a href="https://yakworks.github.io/mkdocs-material-components/cheat-sheet/">Cheat Sheet</a>, <a href="https://www.mkdocs.org/user-guide/writing-your-docs/">Writing your docs</a> 
plugins:
    - search
